NottingHack/hms2

- dev/vagrant-config/nginx/default
Fix suggested by @roberthunt in slack, confirmed that it works
> Updating nginx config to actually work on paths that aren't just /

- app/HMS/Doctrine/CarbonType.php
- app/Providers/DoctrineTypeServiceProvider.php
- config/app.php
Will now return Carbon objects from DB instead of DateTime objects
> Added carbon type to override DateTime type

- app/HMS/Entities/User.php
- app/HMS/Mappings/HMS.Entities.User.dcm.yml
- app/HMS/Traits/Entities/Timestampable.php
- database/migrations/Version20161025122151_add_timestampable_to_user.php
This closes #35 
Added Timestampable trait.
Updated User entity to use it.
> Set User entity as Timestampable

- app/HMS/Entities/User.php
- app/HMS/Mappings/HMS.Entities.User.dcm.yml
- app/HMS/Traits/Entities/Blameable.php
- app/Providers/AuthServiceProvider.php
- config/doctrine.php
- database/migrations/Version20161026184654_add_blameable_columns_to_user.php
Completes #34 Add Blameable Plugin
> Added blameable trait and update user entity to use it

- dev/vagrant-config/scripts/laravel.sh
https://laravel.com/docs/5.3/scheduling
> Vagrant: Add cron job to enable the Task Scheduler

- app/Http/Controllers/Auth/LoginController.php
- resources/views/auth/login.blade.php
> Login: allow both username and email to be used during login

- resources/views/auth/passwords/email.blade.php
- resources/views/auth/passwords/reset.blade.php
Modified the two forms for password reset to match the current state of HMS2 styling.
> Styling of the password reset forms

- resources/views/layouts/app.blade.php
Add Font Awesome to the default layout.
Minor tweak to the existing code that was expecting Font Awesome icons in the footer (apparently I meant to do this some time ago) to use the fa-fw class so they line up better.
> Add Font Awesome

- app/HMS/Auth/KerberosPasswordStore.php
see https://scrutinizer-ci.com/g/NottingHack/hms2/issues/master/files/app/HMS/Auth/KerberosPasswordStore.php?selectedLabels%5B0%5D=9&orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-50586752
> Kerberos setPassword bug

- app/HMS/Entities/User.php
@cooperaj requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/NottingHack/hms2/
> Scrutinizer Auto-Fixes

- app/HMS/Repositories/DoctrineUserRepository.php
- app/Providers/RepositoryServiceProvider.php
few fixes for the User repo that will help us later down the line
> Doctrine user repository

- resources/assets/sass/_settings.scss
- resources/assets/sass/app.scss
- resources/views/auth/register.blade.php
Adds a new class 'form-container' which is good for forms inside other page content.
> Improve layout of registration page.

- app/HMS/Entities/PasswordReset.php
- app/HMS/Entities/Profile.php
- app/HMS/Entities/Role.php
- app/HMS/Entities/User.php
> Return $this on all entity setters

- resources/views/welcome.blade.php
> Fix RegisterInterest link on welcome page

- routes/web.php
Don't need two auth middleware groups
> Routes: cleanup

- dev/vagrant-config/nginx/default
- dev/vagrant-config/scripts/nginx.sh
- resources/views/emails/interestregistered.blade.php
- resources/views/emails/text/interestregistered-plain.blade.php
large rewrite of the nginx config to force all traffic over ssl, this is how production will be
downside is in dev you get a new ssl cert ever vagrant up
close #76
> #76 nginx https

- app/Listeners/Invites/MailInvite.php
- app/Listeners/Invites/RevokeInviteOnUserRegistered.php
- app/Providers/EventServiceProvider.php
As we will be adding lots more later on time to keep the folder clean now
> Move Invite specific listeners into sub folder

- app/HMS/Repositories/Doctrine/DoctrineInviteRepository.php
- app/HMS/Repositories/Doctrine/DoctrineMetaRepository.php
- app/HMS/Repositories/Doctrine/DoctrinePermissionRepository.php
- app/HMS/Repositories/Doctrine/DoctrineProfileRepository.php
- app/HMS/Repositories/Doctrine/DoctrineRoleRepository.php
- app/HMS/Repositories/Doctrine/DoctrineUserRepository.php
- app/HMS/Repositories/InviteRepository.php
- app/HMS/Repositories/MetaRepository.php
- app/HMS/Repositories/PermissionRepository.php
- app/HMS/Repositories/ProfileRepository.php
- app/HMS/Repositories/RoleRepository.php
- app/HMS/Repositories/UserRepository.php
- app/HMS/User/Permissions/RoleManager.php
- app/HMS/User/ProfileManager.php
- app/HMS/User/UserManager.php
- app/Http/Controllers/RoleController.php
- app/Providers/RepositoryServiceProvider.php
This closes #82 by refactoring all the repositories to have interfaces and implementations
I've also added profile and permission repos
and refactored userRepo->create to ->save
> #82 repository interfaces

- app/HMS/Repositories/Doctrine/DoctrineInviteRepository.php
- app/HMS/Repositories/InviteRepository.php
- app/Listeners/Invites/RevokeInviteOnUserRegistered.php
> #75 invite remove

- database/migrations/Version20170206225300_fix_invite_index.php
`php artisan doctrine:migrations:diff` seems to want this
> Fix index on the invites table

- app/HMS/Composers/NavComposer.php
> NavBar: hopefully this will fix it for guests

- app/HMS/Entities/Profile.php
- app/HMS/Mappings/HMS.Entities.Profile.dcm.yml
- app/HMS/User/ProfileManager.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/RoleController.php
- app/Providers/AppServiceProvider.php
- database/factories/ProfileFactory.php
- database/migrations/Version20170226152209_add_profile_dob_field.php
- database/seeds/DatabaseSeeder.php
- database/seeds/ProfileTableSeeder.php
- resources/views/auth/register.blade.php
This should cover adding the DoB field and the DB seeder needs for #29
> #29 profile dob and seeder

- app/HMS/Repositories/Doctrine/DoctrineUserRepository.php
Query fixes for UserRepository->searchLike()
> query-fixes

- config/roles.php
> Roles: add temp and banned member roles

- app/HMS/Repositories/Doctrine/DoctrineRoleRepository.php
- app/HMS/Repositories/RoleRepository.php
- database/seeds/UserTableSeeder.php
> Role Repo: correct usage to findOneByName

- app/Http/Controllers/MembershipController.php
- app/Listeners/Membership/ApprovalEmailOnUserRegistered.php
- app/Mail/InterestRegistered.php
missed theses the first time round
> Role Repo: correct more findOneByName

- resources/views/vendor/pagination/default.blade.php
- resources/views/vendor/pagination/simple-default.blade.php
> Fix #170 by making default Laravel pagination template work with Foundation

- resources/views/labelTemplates/index.blade.php
- resources/views/labelTemplates/show.blade.php
- resources/views/links/index.blade.php
> Style some buttons

- app/Http/Controllers/MetaController.php
- resources/views/meta/index.blade.php
Seems never restricted these routes
> Meta: protect routes with permissions

- app/Console/Commands/Make/GeneratorCommand.php
- app/Providers/RepositoryServiceProvider.php
- config/repositories.php
just to shut up @geeksareforlife
> RepositoryServiceProvider: i cant type

- app/Listeners/Membership/RevokeMembership.php
- config/roles.php
Forgot to do this when building the membership audit
> RevokeMembership: remove all but retained Roles

- app/Console/Commands/Permissions/SyncCommand.php
- app/Console/Kernel.php
- app/HMS/Repositories/Doctrine/DoctrinePermissionRepository.php
- app/HMS/Repositories/PermissionRepository.php
should save having to do this manually during dev
> New artisan command to sync permissions and roles during dev

- resources/assets/js/app.js
- resources/views/partials/memberSearch.blade.php
> MemberSearch: Trying to remove the query param from the search form submission

- app/Events/Users/UserEmailChanged.php
- app/HMS/User/UserManager.php
- app/Listeners/ViMbAdminSubscriber.php
ViMbAdminSubscriber: handle updates to aliases based on change of user email
closes #153
> UserManager: fire event when a user email is changed

- app/HMS/Composers/NavComposer.php
> NavComposer: tell the CSS we need to also highlight parent link

- app/Http/Controllers/Snackspace/TransactionsController.php
- resources/views/snackspace/transaction/index.blade.php
In dev Admin does not have a profile and hence no balance and so you can see his snackspace transactions
> Snackspace: can only view transactions if you have a profile

- app/Console/Commands/Members/YoungHackerAuditCommand.php
- app/Console/Kernel.php
- app/Events/Membership/YoungHackerAuditRequest.php
- app/Listeners/Membership/ApproveNewMembership.php
- app/Listeners/Membership/AuditYoungHackers.php
- app/Mail/Membership/EighteenCongratulations.php
- app/Notifications/Membership/YoungHackerTurnedEighteen.php
- app/Providers/EventServiceProvider.php
- resources/views/emails/membership/eighteenCongratulations.blade.php
- resources/views/emails/membership/membershipReinstated.blade.php
and fixed some typo's
closes #213
> YoungHackerAudit: migrate young hackers on their 18th birthday

- config/roles.php
- routes/web.php
> 279 password reset bug

- resources/views/vendor/cookieConsent/dialogContents.blade.php
Reinstate the class tag that the javascript side of this is relying on to do its job
> Really fix #269

- resources/views/membership/showDetails.blade.php
and some indentations
and div form overlap
> Membership: Fix the textarea width for reject details

- package.json
- resources/assets/js/app.js
- resources/assets/sass/app.scss
- resources/views/layouts/app.blade.php
- yarn.lock
> use angel-vladov/select2-bootstrap-theme to theme select2 boxes

- app/Events/Users/UserPasswordChanged.php
- app/Exceptions/Handler.php
- app/Http/Controllers/Auth/ChangePasswordController.php
- app/Http/Middleware/TrimStrings.php
- app/Listeners/Users/EmailOnPasswordChange.php
- app/Notifications/Users/PasswordChanged.php
- app/Providers/EventServiceProvider.php
- resources/views/user/changePassword.blade.php
- routes/web.php
route not yet linked but
https://hmsdev/change-password
Closes #157
> #157 change password

- app/HMS/Entities/LabelTemplate.php
> LabelTemplate: fix bug in updateWithRequest

- package.json
- webpack.mix.js
- yarn.lock
https://laravel.com/docs/5.7/mix#browsersync-reloading
now you can run
`npm run watch-poll`
and it will push changes to the browser
> Mix: enable browserSync for hmsdev

- config/doctrine.php
Fix bug found in recent `vagrant up` on a fresh clone
> Doctrine: update config to be in sync with vendor

- .editorconfig
Quick update to keep our blade and vue files styled
> EditorConfig for blade and vue files

- app/HMS/Entities/Invite.php
- app/HMS/Mappings/HMS.Entities.Invite.dcm.yml
- database/migrations_doctrine/Version20190109010523_alter_invites_soft_delete.php
> Invites: remove soft delete

- app/HMS/Entities/Banking/BankTransaction.php
- app/HMS/Factories/Banking/BankTransactionFactory.php
- app/HMS/Mappings/HMS.Entities.Banking.BankTransaction.dcm.yml
- app/Http/Controllers/Api/TransactionUploadController.php
- app/Listeners/Banking/SaveNewTransactions.php
- database/migrations_doctrine/Version20190108233223_alter_bank_transactions_to_pennies.php
- database/seeds/BankTransactionTableSeeder.php
- resources/views/bankTransactions/edit.blade.php
- resources/views/bankTransactions/index.blade.php
- resources/views/bankTransactions/listUnmatched.blade.php
> BankTransaction: store amounts as pennies

- app/Mail/InterestRegistered.php
- app/Mail/Membership/MembershipComplete.php
- app/Mail/Membership/MembershipReinstated.php
- database/migrations_doctrine/Version20190109152643_remove_unneeded_meta_entries.php
These are hang overs from HMS1
> Meta: clean up some unneeded entries

- app/Mail/Membership/MembershipMayBeRevoked.php
- app/Mail/Membership/MembershipRevoked.php
- app/Mail/MembershipDetailsApproved.php
- database/migrations_doctrine/Version20190110025754_meta_so_bank_id.php
When I clean out meta earlier I forgot to implement this change to get the so details from the Bank table
> Membership: fix email to use sort code and account number from Bank

- .gitignore
- app/Providers/ComposerServiceProvider.php
- composer.json
- composer.lock
- resources/views/layouts/footer.blade.php
need to do `git describe --always --tags --dirty >version` on production deploy's
Close #315
> Version: display version in footer based on git tags/status

- app/Console/Commands/Database/MigrateInstrumentaionCommand.php
- app/Events/Roles/UserAddedToRole.php
- app/Events/Roles/UserRemovedFromRole.php
- app/HMS/Entities/Instrumentation/MacAddress.php
- app/HMS/Entities/RoleUpdate.php
- app/HMS/Mappings/HMS.Entities.GateKeeper.AccessLog.dcm.yml
- app/HMS/Mappings/HMS.Entities.Instrumentation.MacAddress.dcm.yml
- app/HMS/Mappings/HMS.Entities.RoleUpdate.dcm.yml
- app/Http/Controllers/MembershipController.php
- app/Listeners/Membership/RevokeMembership.php
- app/Listeners/Membership/WarnMembershipMayExpire.php
- app/Listeners/RoleUpdateLogger.php
- app/Mail/Membership/MembershipMayBeRevoked.php
- app/Mail/Membership/MembershipRevoked.php
- app/Mail/MembershipDetailsApproved.php
- app/Providers/AppServiceProvider.php
- config/hms.php
- config/roles.php
- database/migrations_doctrine/Version20190114061839_fix_access_logs_and_addresses.php
- database/migrations_doctrine/Version20190114063308_alter_role_update_add_update_by.php
- dev/reseed.sh
- dev/vagrant-config/scripts/laravel.sh
Bunch of fixes but mainly that prep for the big one
Live DB migration script
Colse #256
> Instrumentation migration

- dev/googleCalendarImport/.editorconfig
- dev/googleCalendarImport/.gitignore
- dev/googleCalendarImport/composer.json
- dev/googleCalendarImport/migrate.php
- dev/googleCalendarImport/src/MigrateGoogle.php
Changed my mind, might at well have this in master so I can keep it up to date
its very quick and dirty and done as a separate project in the dev folder anyway
Need to get a hold of `nottinghack-hms-cf36c6256dae.json` and put in the `dev/googleCalendarImport` folder
to use navigate to `dev/googleCalendarImport`
`composer install`
`./migrate.php`
> Bookings: import from google calendar api script

- app/HMS/Entities/Members/Project.php
- app/HMS/Entities/Snackspace/Transaction.php
- app/HMS/Entities/Snackspace/TransactionType.php
- resources/sass/_variables.scss
- resources/sass/app.scss
- resources/views/bankTransactions/listUnmatched.blade.php
- resources/views/gateKeeper/rfidTags/index.blade.php
- resources/views/layouts/footer.blade.php
- resources/views/members/box/index.blade.php
- resources/views/members/project/index.blade.php
- resources/views/meta/index.blade.php
- resources/views/pages/access.blade.php
- resources/views/role/index.blade.php
- resources/views/snackspace/transaction/index.blade.php
- resources/views/tools/tool/index.blade.php
- resources/views/user/index.blade.php
> Responsive tables

- app/Http/Controllers/RoleController.php
- app/Listeners/RoleUpdateLogger.php
- composer.lock
- config/roles.php
- resources/js/components/AddUserToTeamModal.vue
- resources/js/components/SelectTwo.vue
- resources/js/vue.js
- resources/views/role/index.blade.php
- routes/web.php
still a little rough around the edges
close #250
> Role: add ability to add a user to a team

- app/HMS/Entities/GateKeeper/Door.php
- app/HMS/Mappings/HMS.Entities.GateKeeper.Door.dcm.yml
- app/HMS/Mappings/HMS.Entities.GateKeeper.Zone.dcm.yml
- config/roles.php
- database/migrations_doctrine/Version20190119204450_alter_zone_permission_length.php
- database/migrations_doctrine/Version20190119205657_updated_populated_zones.php
- database/migrations_doctrine/Version20190119211213_alter_doors_remove_permission_code.php
- database/migrations_doctrine/Version20190121235231_update_zone_outside_permission.php
adding new `gatekeeper.zoneEntry.*` permissions on the zones that gatekeeper can check against to see if a member is allowed access
> Zone: add permission for zones

- app/Http/Controllers/Banking/BankTransactionsController.php
- resources/sass/app.scss
- resources/views/bankTransactions/index.blade.php
- resources/views/instrumentation/eventsForService.blade.php
- resources/views/layouts/navbar.blade.php
- resources/views/pages/access.blade.php
- resources/views/pages/admin.blade.php
- resources/views/snackspace/transaction/index.blade.php
- resources/views/user/index.blade.php
closes #212 
might go back and add an email me this button later
> Standing Order details

- app/Http/Controllers/Snackspace/TransactionsController.php
- config/navigation.php
- config/roles.php
- resources/views/snackspace/transaction/create.blade.php
- resources/views/snackspace/transaction/index.blade.php
- routes/web.php
> Snackspace Transactions: Allow entry of manual snackspace transactions

- Vagrantfile
- app/Console/Commands/Database/RefreshViewsCommand.php
- app/Http/Middleware/VerifyCsrfToken.php
- app/Jobs/PostGitDeployedJob.php
- app/Listeners/GitDeployedListener.php
- app/Notifications/PostGitDeployedResults.php
- composer.json
- composer.lock
- config/gitdeploy.php
- dev/vagrant-config/scripts/laravel-queue.sh
- resources/views/emails/postGitDeployed.blade.php
- routes/console.php
web hooks for rommie already setup
just need to rework the permission sync command
closes #316
> #316 automatic deployment

- app/Console/Commands/Make/stubs/doctrine-repository.stub
- app/Console/Commands/Make/stubs/repository-interface.stub
- app/HMS/Entities/Snackspace/PurchasePayment.php
- app/HMS/Repositories/Snackspace/Doctrine/DoctrinePurchasePaymentRepository.php
- app/HMS/Repositories/Snackspace/Doctrine/DoctrineTransactionRepository.php
- app/HMS/Repositories/Snackspace/PurchasePaymentRepository.php
- app/HMS/Repositories/Snackspace/TransactionRepository.php
- app/Jobs/Snackspace/ProcessTransaction.php
- config/repositories.php
same as sp_process_transaction
closes #354
> Snackspace: Update purchasePayments when we add a Transaction

- app/HMS/Repositories/Doctrine/DoctrineUserRepository.php
- app/HMS/Repositories/UserRepository.php
- app/Http/Controllers/Api/SearchController.php
- resources/js/components/AddUserToTeamModal.vue
- resources/js/components/MemberSearch.vue
- resources/js/components/MemberSelectTwo.vue
updates AddUserToTeamModal to use this new option
fix #439
> Search: allow limiting to only MEMBER_CURRENT role

- app/Events/Governance/AttendeeCheckIn.php
- app/Events/Tools/BookingCancelled.php
- app/HMS/Repositories/Snackspace/Doctrine/DoctrineTransactionRepository.php
- app/Http/Controllers/Api/Governance/CheckInController.php
- app/Http/Controllers/Banking/AccountController.php
- app/Http/Controllers/Banking/BankTransactionsController.php
- app/Http/Controllers/GateKeeper/AccessLogController.php
- app/Http/Controllers/MembershipController.php
- app/Jobs/Banking/AccountAuditJob.php
and reconciled transaction
close #401
> Membership: audit Account after linking accounts

- resources/views/members/box/index.blade.php
Add text to explain that you need to be in the space to see the print link.
> Update text on Labels page.

- app/HMS/Repositories/Banking/BankTransactionRepository.php
- app/HMS/Repositories/Banking/Doctrine/DoctrineBankTransactionRepository.php
- app/Http/Controllers/Banking/Bank/BankBankTransactionController.php
- app/Jobs/Banking/SaveNewOFXTransactionsJob.php
- composer.json
- composer.lock
- config/hms.php
- config/navigation.php
- config/roles.php
- package-lock.json
- package.json
- resources/js/app.js
- resources/views/banking/banks/index.blade.php
- resources/views/banking/banks/show.blade.php
- resources/views/banking/banks/transactions/ofx-upload.blade.php
- routes/web.php
feature is disabled by default
close #494
> BankTransaction: allow OFX upload

- app/Console/Commands/Database/MigrateMembersAreaCommand.php
- app/Console/Commands/Permissions/SyncCommand.php
- app/HMS/Entities/Banking/Account.php
- app/HMS/Mappings/HMS.Entities.Banking.Account.dcm.yml
- app/Http/Controllers/AdminController.php
- app/Jobs/Banking/SaveNewOFXTransactionsJob.php
- config/roles.php
- resources/views/emails/banking/auditIssues.blade.php
- resources/views/role/show.blade.php
- resources/views/statistics/member_stats.blade.php
> #491 migrate members area command

- app/Http/Controllers/Api/UserController.php
- routes/api.php
bit of a fudge to give an User api end point that just give the current user with having to pass in you own id
> Api/UserController: add index method to just return the current user

- app/Http/Controllers/Snackspace/VendingMachineController.php
> money_format is deprecated, change to NumberFormatter

- app/HMS/Tools/ToolManager.php
- app/Http/Controllers/Tools/ToolController.php
- resources/views/tools/tool/show_users.blade.php
- routes/web.php
> ToolContoller: add dedicated revoke method

- config/meta.php
- resources/views/card/access.blade.php
- resources/views/gatekeeper/space_access.blade.php
Add in Ashley Street door code into blade.
> Ashley Street Doorcode addition

- database/seeds/ContentBlockSeeder.php
- resources/views/emails/membership/membershipExUnderPaid.blade.php
- resources/views/emails/membership/membershipRevoked.blade.php
- resources/views/emails/membership/membershipRevokedDueToUnderPayment.blade.php
- resources/views/emails/membership/membershipUnderPaid.blade.php
Andrew and I have taken a look through and think this might read a bit better
> Minimum membership notification wording

- app/Http/Controllers/Api/SpaceApiController.php
- config/branding.php
- resources/views/layouts/footer.blade.php
- adds link to our hachyderm/mastodon
- adds `rel="me"` attr to all social links in the footer
> Mastodon social link

- app/Http/Controllers/EmailController.php
- resources/views/emailMembers/draft.blade.php
- routes/web.php
> Add endpoint to clear emailMembers cache

- app/Http/Controllers/Tools/ToolController.php
> Fix tool time calcultion

- app/HMS/Entities/Tools/Tool.php
- app/HMS/Mappings/HMS.Entities.Tools.Tool.dcm.yml
- app/HMS/Tools/ToolManager.php
- app/Http/Controllers/Tools/ToolController.php
- database/migrations_doctrine/Version20240622203546_add_tool_hidden_flag.php
- resources/views/tools/tool/edit.blade.php
- resources/views/tools/tool/index.blade.php
- resources/views/tools/tool/show.blade.php
> Make tools hideable

- resources/views/members/project/index.blade.php
Currently only possible to view the first 15 projects
> Add pagination to Projects

- app/HMS/Prometheus/Collectors/Governance/MeetingCollector.php
> getProxies should be getAttendees

- app/HMS/Prometheus/Collectors/Governance/MeetingCollector.php
uhh hopefully the last one of these...
> Add checked_in and represented_proxies

- app/Listeners/Governance/RegisterOfMembersLogger.php
There are some entries with empty dates who are now ex-members
> Missing import from RegisterOfMembersLogger
