NottingHack/hms2

app/HMS/Repositories/RoleRepository.php, app/Http/Controllers/Auth/RegisterController.php
This a quick fix to allow the registration process to continue working as it was before. We've changed around the migrations a bit and the 'member' role I was assigning no longer exists which broke the registration process. I know this will change in the future but this gets the application working again in the meantime.
=> Assign current member role during registration

resources/assets/sass/app.scss
Auto-generates a class for each of the Foundation colour palette colours which works on <a> tags, in the same way that there are such classes for buttons, callouts etc.
Closes #60
=> Enable colouring of links using the Foundation colour palette.

gulpfile.js, resources/assets/js/app.js, resources/views/layouts/app.blade.php
jQuery and Foundation get combined into one JS file.
app.js (site global JS) gets compiled with Webpack into another.
app.js also now contains the initialisation code for Foundation plugins.
All these files are included in the default layout.
=> Fix JavaScript build and bundling and make Foundation JS plugins work.

dev/vagrant-config/laravel/.env, dev/vagrant-config/scripts/kerberos.sh
this little tweak allows me and others vagrant up the same clone across different machines with out breaking the kerberos logins when the key tab is replaced
=> Vagrant: move keytab inside the vagrant box

app/HMS/Mappings/HMS.Entities.Role.dcm.yml
Inverse mapping only needs to define the `mappedBy` pram
We also don’t need the cascade delete’s as both User and Role are soft deletable the many to many does magic they won’t show
This was introduced by cb60601
=> Correct Role User many to many mapping

app/Console/Commands/Permissions/DefaultsCommand.php, app/Events/MembershipInterestRegistered.php, app/Events/Roles/RoleCreated.php, app/Events/Roles/UserAddedToRole.php, app/Events/Roles/UserRemovedFromRole.php, app/HMS/Entities/Role.php, app/HMS/Mappings/HMS.Entities.Role.dcm.yml, app/HMS/User/Permissions/RoleManager.php, app/HMS/User/UserManager.php, config/roles.php, database/migrations/Version20170423104651_add_email_slack_retained_to_role.php, resources/views/role/edit.blade.php, resources/views/role/show.blade.php
Some updates to the Role table and manager 
new columns
* email email address for team roles, used for automatic team email updates and notifications to teams
* slackChannel used to post notifications to team channels
* retained flag for roles that should be retained during member audit changes
Add the first two teams (Membership & Trustees) as there will required notifications during my upcoming registration stuff
rework the user and role managers so generation of events when user is added to/removed from a role can happen in just one file
fixed the front end so the remove user from role buttons work
=> Role update

app/HMS/Entities/Banking/Account.php, app/HMS/Entities/Profile.php, app/HMS/Entities/User.php, app/HMS/Factories/Banking/AccountFactory.php, app/HMS/Mappings/HMS.Entities.Banking.Account.dcm.yml, app/HMS/Mappings/HMS.Entities.User.dcm.yml, app/HMS/Repositories/Banking/AccountRepository.php, app/HMS/Repositories/Banking/Doctrine/DoctrineAccountRepository.php, app/HMS/Repositories/Doctrine/DoctrineUserRepository.php, app/HMS/Repositories/UserRepository.php, app/Providers/RepositoryServiceProvider.php, composer.lock, database/migrations/Version20170426184421_add_account_table.php, database/migrations/Version20170502204811_add_user_account_relation.php, resources/assets/js/role.js
This covers the payment ref table and generation
another small step towards my work on #111
=> Accounts paymentref

.travis.yml, dev/vagrant-config/nginx/default, dev/vagrant-config/scripts/bootstrap.sh, dev/vagrant-config/scripts/finish.sh, dev/vagrant-config/scripts/kerberos.sh, dev/vagrant-config/scripts/php.sh
after doing fresh vagrant up one will need to do the following if your working with an existing git clone
```
php artisan cache:clear
php artisan view:clear
```
closes #129
=> Vagrant: update to php7.1

app/HMS/Entities/Banking/Account.php, app/HMS/Entities/Invite.php, app/HMS/Entities/Link.php, app/HMS/Entities/Meta.php, app/HMS/Entities/PasswordReset.php, app/HMS/Entities/Profile.php, app/HMS/Entities/Role.php, app/HMS/Entities/User.php, app/HMS/Factories/Banking/AccountFactory.php, app/HMS/Mappings/HMS.Entities.PasswordReset.dcm.yml, app/HMS/Mappings/HMS.Entities.User.dcm.yml, app/Http/Controllers/Auth/RegisterController.php, resources/views/partials/flash.blade.php, resources/views/partials/flashModal.blade.php, resources/views/role/edit.blade.php, storage/debugbar/.gitignore
Bunch of fixes from the recent upgrade's
=> Upgrade fixes

resources/assets/js/app.js, resources/assets/js/bootstrap.js, resources/views/layouts/app.blade.php, resources/views/partials/flashModal.blade.php, webpack.mix.js
https://laravel.com/docs/5.4/mix#vendor-extraction
=> JS: need to server the manifest file when using extract

app/Providers/RepositoryServiceProvider.php, config/repositories.php
Closes #130
Does not yet look into deferring the binding of some repositories
This is going to cause all sort of merge conflicts will all my outstanding PR's so either this goes in first and I fix al them of this goes in last
=> RepositoryServiceProvider: dynamic loading of out repos

app/Console/Commands/Make/EntityMakeCommand.php, app/Console/Commands/Make/FactoryMakeCommand.php, app/Console/Commands/Make/GeneratorCommand.php, app/Console/Commands/Make/MakeCommand.php, app/Console/Commands/Make/MappingMakeCommand.php, app/Console/Commands/Make/RepositoryImplementationMakeCommand.php, app/Console/Commands/Make/RepositoryInterfaceMakeCommand.php, app/Console/Commands/Make/stubs/doctrine-repository.stub, app/Console/Commands/Make/stubs/entity.stub, app/Console/Commands/Make/stubs/factory.stub, app/Console/Commands/Make/stubs/mapping.stub, app/Console/Commands/Make/stubs/repository-interface.stub, app/Console/Kernel.php
Usage:
`php artisan hms:make GateKeeper/RfidTag`
`hms:make` will create boilerplate files for Entity, Mapping, Repository Interface, Repository Implementation (docrtine) and Factory
each file can also be generated individually using the appropriate command from below
```
hms:make                            Create a new Entity/Mapping/Interface/Implementation/Factory all in one go.
hms:make:entity                     Create a new Entity
hms:make:factory                    Create a new Factory
hms:make:mapping                    Create a new Mapping
hms:make:repository:implementation  Create a new Repository Implementation
hms:make:repository:interface       Create a new Repository Interface
```
=> Console: HMS Entity boilerplate creation helpers

app/HMS/Composers/NavComposer.php, config/navigation.php, database/seeds/UserTableSeeder.php, dev/vagrant-config/laravel/.env, resources/assets/sass/app.scss, resources/views/layouts/app.blade.php
Move navigation to be a menu bar, except on small screens where you get a Menu button to press which shows a nice vertical menu instead.
The menu bar has dropdowns for sub-items such as in Admin, and the small screen menu puts those in an expandable accordion.
This had a number of ripple effects through the overall page structure, moving some margins and padding etc. around so that the small screen menu would appear neatly in the right place.
=> Overhaul navigation

resources/assets/js/app.js, resources/assets/js/bootstrap.js, resources/views/layouts/app.blade.php
as per changed in laravel 5.4.23
https://github.com/laravel/laravel/pull/4260
=> Frontend: Use CSRF token from meta tag, instead of window.Laravel object

app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/MembershipController.php, app/Http/Controllers/UserController.php, resources/assets/js/app.js, resources/views/auth/register.blade.php, resources/views/membership/editDetails.blade.php, resources/views/user/edit.blade.php
We should be sending everything over the wire in ISO_8601 format, but as we don't yet have date pikers for all browsers this catches anyone trying to submit a UK format
=> Date format work around to change dd/mm/yyyy to yyyy-mm-dd on submit

app/HMS/Entities/GateKeeper/Pin.php, app/HMS/Entities/GateKeeper/PinState.php, app/HMS/Entities/GateKeeper/RfidTag.php, app/HMS/Entities/GateKeeper/RfidTagState.php, app/HMS/Entities/Members/Project.php, app/HMS/Entities/Members/ProjectState.php, app/HMS/Entities/Snackspace/Transaction.php, app/HMS/Entities/Snackspace/TransactionState.php, app/HMS/Entities/Snackspace/TransactionType.php, app/HMS/Factories/GateKeeper/PinFactory.php, app/HMS/Repositories/Snackspace/Doctrine/DoctrineTransactionRepository.php, resources/views/members/project/index.blade.php, resources/views/members/project/show.blade.php
This is some refactoring to extract what are essentially enumerated types (which PHP doesn't support) into separate classes to avoid cluttering the domain entity classes. I have also removed the code duplication that was present in the `$statusStrings` which will prevent them from becoming out of sync with their numeric values.
So `Project::PROJECT_ACTIVE` is now simply `ProjectState::ACTIVE`
=> Extract enums for entites

app/Providers/AppServiceProvider.php, config/app.php, config/database.php, config/logging.php, config/mail.php, config/queue.php, config/services.php, config/session.php, config/view.php, dev/vagrant-config/laravel/.env
so this Is really picking up a lot of changes to the config files that were missed in out bigger Laravel version updates
the main one related to queue worker on rommie is the new env vars 
`REDIS_DB=`
`REDIS_CACHE_DB=`
as we share one Redis instance at the space both trustee tools and hms2 staging were using db 0 in redis
with these setting we can segregate them 
rommie hsm2 will use 2 & 3, trustees tools uses 10 & 11
holly hms2 will use 0 & 1
=> Fix queue worker

app/HMS/Entities/Banking/Stripe/Event.php, app/HMS/Mappings/HMS.Entities.Banking.Stripe.Charge.dcm.yml, app/HMS/Mappings/HMS.Entities.Banking.Stripe.Event.dcm.yml, app/HMS/Repositories/Banking/Stripe/Doctrine/DoctrineEventRepository.php, app/HMS/Repositories/Banking/Stripe/EventRepository.php, app/Jobs/Banking/Stripe/Webhooks/EventHandler.php, app/Jobs/Banking/Stripe/Webhooks/HandleChargeDisputeClosedJob.php, app/Jobs/Banking/Stripe/Webhooks/HandleChargeDisputeCreatedJob.php, app/Jobs/Banking/Stripe/Webhooks/HandleChargeDisputeFundsReinstatedJob.php, app/Jobs/Banking/Stripe/Webhooks/HandleChargeDisputeFundsWithdrawnJob.php, app/Jobs/Banking/Stripe/Webhooks/HandleChargeDisputeUpdatedJob.php, app/Jobs/Banking/Stripe/Webhooks/HandleChargeRefundUpdatedJob.php, app/Jobs/Banking/Stripe/Webhooks/HandleChargeRefundedJob.php, app/Jobs/Banking/Stripe/Webhooks/HandleChargeSucceededJob.php, config/repositories.php, database/migrations_doctrine/Version20190815051316_add_stripe_events_table.php
add a new Event entity to track when webhook handling is completed
refactor all the Webhook Handler jobs adding some abstraction to cut down code reuse and use the new Event tracking
this should help prevent duplicate event handling by making your event processing idempotent
=> Stripe: new Event entity and webhook refactor

resources/views/layouts/app.blade.php
Tested on mobile and desktop.
Prevents the 15px horizontal scrollbar from appearing. Since the
horizontal scrollbar was altering the height of the page very
slightly, some text fields would cause the page to jump about while
typing (e.g. on the login page).
The change overloads the .row horizontal margin from bootstrap and
adds some negative margin to the navbar.
=> Fix for 15px horizontal scrollbar

app/Listeners/Membership/ApproveNewMembership.php, app/Mail/Membership/MembershipComplete.php, config/meta.php, config/roles.php, resources/views/card/access.blade.php, resources/views/emails/membership/membershipComplete.blade.php
As discussed with Andrew and the membership team - since we no longer ask members to come to the next open night to collect their card, we have been emailing the user with their gatekeeper pin and link to instructions on the wiki. Since this pin can only be used once, unless being reactivated, we do not see any disadvantages to these changes, and will save a great deal of admin.
The changes also allow the pin to be shown within HMS, if it's set to enrol, regardless of what groups a user is in.
Feedback appreciated, especially if we've missed something re pin activations.
cheers
Aaron
=> Provide members with gatekeeper pin in setup email

resources/views/statistics/member_stats.blade.php
Raised in #comms on Discord by bauhaus1919
there's no rush to deploy obviously
=> Correct spelling errors in membership conversion stats

app/Http/Controllers/MembershipController.php
sorry for the mass of PRs this weekend - this one is to avoid something which happened today where another membership team member accepted a request after i'd already rejected it. We were possibly on the same page already.
=> Prevent rejected member approval until its been updated by user

app/Console/Kernel.php, app/HMS/Helpers/Discord.php, app/HMS/Repositories/Doctrine/DoctrineProfileRepository.php, app/HMS/Repositories/ProfileRepository.php, app/Http/Controllers/UserController.php, app/Jobs/DiscordAuditJob.php, routes/console.php, routes/web.php
This adds a daily job which runs at 12:15 each day. It goes through each user on Discord with the "Current Member" role and makes sure they are actually a current member. This is needed to ensure HMS team roles are kept in sync with Discord, which can't happen if someone changes their Discord username (either forced, due to legacy discriminator, or preference).
The user will receive a DM when this happens with an explanation and link to update their details.
To make it as easy as possible for a user to update their Discord username, a new web route has been added `/profile` which redirects to `/users/{current user}/edit`.
=> Daily Discord Audit Job

app/HMS/Entities/Profile.php, app/HMS/Entities/User.php, app/HMS/Helpers/Discord.php, app/HMS/Mappings/HMS.Entities.Profile.dcm.yml, app/HMS/Repositories/Doctrine/DoctrineProfileRepository.php, app/HMS/Repositories/ProfileRepository.php, app/HMS/User/ProfileManager.php, app/Jobs/DiscordAuditJob.php, app/Listeners/RoleUpdateDiscordUpdater.php, app/Notifications/Users/DiscordRegistered.php, database/migrations_doctrine/Version20240622102424_add_discord_user_snowflake.php, resources/views/user/show.blade.php
The audit job should take care of populating missing snowflakes.
I think all instances of `findMemberByUsername` have been replaced with a `findMemberByProfile` which will attempt to find the username by their snowflake first. Eventually I might strip out the `findMemberByUsername` stuff.
The audit job will update the `discordUsername` field if it appears to have changed. Keeping the username is useful for showing it in profile and also for the search.
Still tempted to add a separate page for linking Discord at some point, maybe with a card on the home view, but this should hopefully fix any issues for now.
=> Use Discord User Snowflake for Role management and Notifications

app/Http/Controllers/Auth/RegisterController.php, resources/views/auth/register.blade.php
This adds a checkbox to say the future-member has read and agreed to the nottinghack rules
client side validation also prevents the form from being submitted, but in the worst case:
=> Add field to 'agree to rules'

app/HMS/Prometheus/Collectors/Governance/MeetingCollector.php, app/Providers/PrometheusServiceProvider.php
Thinking live dashboard in the hour running up to the meeting.
Might make sense to switch to `findNext()` instead of `paginateAll` but it would be nice to back fill previous AGMs. Happy to make a separate PR for that later if you like.
Also might generally be a bit database heavy since it's pulling User objects instead of counts? (edit: are collections lazy loaded?)
=> Add prometheus collector for meetings

app/HMS/Mappings/HMS.Entities.Snackspace.Product.dcm.yml, app/Http/Controllers/Snackspace/ProductController.php, database/migrations_doctrine/Version20241120222758_alter_snackspace_short_description_max_length.php
@daniel1111 identified the issue, here's a fix to hms
Issue with snackspace balance not being reduced for certain products is due to the short description being too long for a variable used in `sp_vend_success` 
https://github.com/NottingHack/database/blob/f2dcb2507aabd0530d80c9b056ac08dbe11fd347/procedures/sp_vend_success.sql#L25
This changes the validation length to 25 and restores the `short_description` field back to how it was before hms2
Descriptions have been adjusted in the production hms deployment to be a maximum of 25
Might want to go back and look for those recent vend failures - the product ids causing the issue were 342, 345 and 336. They have shorter names now.
=> Set snackspace product max short_description lengthto 25

app/Notifications/Governance/Proxy/NotifyTrusteesProxyCancelled.php, app/Notifications/Governance/Proxy/NotifyTrusteesProxyRegistered.php
I remembered seeing that there were notifications for this, but noticed we weren't getting any. Not tested, don't have a dev setup for Slack.
=> Add variables to anonymous function scope for Trustee proxy notifications to Slack

app/HMS/Entities/Role.php, app/HMS/Helpers/Discord.php, app/Notifications/Banking/AuditResult.php, app/Notifications/NewMemberApprovalNeeded.php, app/Notifications/NotificationSensitivityInterface.php, app/Notifications/NotificationSensitivityType.php, app/Notifications/NotifyIncommingRoleEmail.php
Adds a new interface to allow notification handle whether it should go to the member / team channel on Discord.
Membership `AuditResult` will become public so you can see it again.
Adds caching to channels in Discord helper.
=> Notification sensitivity

app/HMS/Entities/Role.php, app/Mail/Membership/MembershipComplete.php, app/Mail/Membership/MembershipReinstated.php, config/hms.php, config/meta.php, resources/views/emails/membership/membershipComplete.blade.php, resources/views/emails/membership/membershipReinstated.blade.php, resources/views/governance/proxies/designate_link.blade.php, resources/views/team/index.blade.php
This separates some of the trustee / team slack bits so that the team slack integration can be safely disabled (I think!) by leaving `TEAM_SLACK_WEBHOOK` environment variable unset. It also changes the wording of the membership complete / reinstated email to refer to Discord / Slack based on features.
=> Slack stuff

app/Listeners/ViMbAdminSubscriber.php
Noticed while trying to figure out if there was an issue with password resets (more than likely just hotmail trashing our emails).
Not actually sure if correct I think it's right?
=> ViMbAdmin: Fix undefined $role on userEmailChanged
